import type { Metadata } from 'next';
import { Darumadrop_One } from 'next/font/google';
import './globals.css';

const darumadrop = Darumadrop_One({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={darumadrop.className}>
        <div className="bg-red-300 p-4">メインレイアウト</div>
        {children}
      </body>
    </html>
  );
}
